language: node_js
services:
  - docker
node_js:
  - "8"
  - "9"
  - "10"
cache:
  npm: true
  directories:
    - ./node_modules
  override:
    - npx cypress verify
before_install:
  - npm i -g npm@6.13.4
before_script:
  - npm run build
script:
  - npm run lint
  - npm run lint:css
deploy:
    # automation build docker images for release branch
  - provider: script
    skip_cleanup: true
    script: /bin/sh travis/docker.sh
    on:
      branch: $RELEASE_BRANCH
  - provider: script
    skip_cleanup: true
    script: /bin/sh travis/release.sh
    on:
      branch: $RELEASE_BRANCH
  # automation build docker images for main branch
  - provider: script
    skip_cleanup: true
    script: /bin/sh travis/docker.sh
    on:
      branch: $MAIN_BRANCH

